"""
This lists the information specific to the cluster you are running Kiwi-GA on.
This file is to be modified by end users to make sure a working job script can be generated by
pre_run_check.py.
Make sure the right settings are chosen and the correct modules are imported.
"""

username = "sanderv"
codedir = "Binary-Kiwi-GA"
cores_per_node = 48
max_wall_time = "7"  # In minutes, this has to be a string.
time_per_gen = 1.1  # in hours
scratch_loc = "/scratch/sanderv/"
home_loc = "/home/sanderv/"

# For VSC Accounting and such, can leave empty if not applicable
extra_sbatch = """
#SBATCH --partition=normal
#SBATCH --output=/home/sanderv/%s_run.log
#SBATCH --error=/home/sanderv/%s.log
"""

# For VSC
#modules = """
#module load cluster/genius/scientific_computing
#module load intel/2023a
#module load SciPy-bundle/2023.07-iimkl-2023a
#module load matplotlib/3.7.2-iimkl-2023a
#"""

# # For Snellius
# modules = """
# module load 2021
# module load foss/2021a
# module load Python/3.9.5-GCCcore-10.3.0
# """

# For Pleiads
modules = """
module load anaconda
conda activate kiwi
"""
